
// í™˜ê²½ì„¤ì • ì°½ prefab >> í•˜ì´ì–´ë¼í‚¤ ì°½ì— ì˜¬ë ¤ë‘ê³ ,
// ë„ìš°ëŠ” í‚¤ í˜¹ì€ ë²„íŠ¼ë§Œ ì§€ì •í•˜ë©´ ì–´ë””ì„œë“  ë¶ˆëŸ¬ì˜¤ê¸° ê°€ëŠ¥!!
using NUnit.Framework;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using TMPro;


// ë‚˜ì¤‘ì— ìŒëŸ‰, í‚¤ì§€ì •, í•´ìƒë„ ì¡°ì‘ í•„ìš”
public class SettingPanelScript : MonoBehaviour
{

    public GameObject SettingPanel;


    private void Update()
    {
        if (Input.GetButtonDown("Cancel"))
        {
            OnSettingExit();
        }
    }

    public void OnMasterVolumeChanged(float volume)
    {
        SoundManager.Instance.SetAudioVolume(EAudioMixerType.Master, volume);
    }

    public void OnBGMVolumeChanged(float volume)
    {
        SoundManager.Instance.SetAudioVolume(EAudioMixerType.BGM, volume);
    }

    public void OnSFXVolumeChanged(float volume)
    {
        SoundManager.Instance.SetAudioVolume(EAudioMixerType.SFX, volume);
    }

    // ğŸ”‡ ë²”ìš© ë®¤íŠ¸ í•¨ìˆ˜
    public void ToggleMuteByIndex(int mixerTypeIndex)
    {
        EAudioMixerType type = (EAudioMixerType)mixerTypeIndex;
        SoundManager.Instance.SetAudioMute(type);
    }

    public void OnSettingIn()
    {
        SettingPanel.SetActive(true);
    }
    public void OnSettingExit()
    {
        SettingPanel.SetActive(false);
    }
}